### ISSUE TITLE
Toggle Function

### ISSUE THREAD

**Issue by maxflorex** [makaroni4/focused_youtube#4]
Hi there!
 
Love your extension, here's an easy and useful suggestion for it: ADD A TOGGLE BUTTON to disable/enable the functionality, it will be pretty cool.

Cheers

**Comment by makaroni4** [comment]
Hi Max 👋 

Nice idea, although I feel like it defeats the purpose of the extension 🙈 

💡 There's already a toggle for temporarily disabling the extension on [chrome://extensions](chrome://extensions) page:

![Screenshot 2022-12-12 at 20 02 11](https://user-images.githubusercontent.com/768070/207132185-7cd2f982-a8f0-45cf-8ad6-e13d56c97240.png)

Maybe you have a specific use case in mind?

**Comment by makaroni4** [comment]
Just FYI I've added a toggle to show/hide the comments section: https://github.com/makaroni4/focused_youtube#-an-option-to-showhide-the-comments-section – I guess comments are useful to check timestamps, for example.

Let's make it a bit hard to disable the extension (via chrome://extensions), otherwise it defeats its purpose. 

Let's stay focused ❤️ 🙏
