### ISSUE TITLE
Comment option missing

### ISSUE THREAD

**Issue by popema06** [makaroni4/focused_youtube#44]
If you have comments enabled, there is no option to either report someone else's comment or edit/delete your own.

**Comment by KParthSingh** [comment]
Mhm try turning off and then turning on comments option again.

**Comment by popema06** [comment]
I wasn't referring to enabeling or disabling the comments section itself. I was referring to the option for each comment that appears when you hover over it, as I tried to describe in the detailed description of this issue.

**Comment by makaroni4** [comment]
Hola @popema06 @KParthSingh 👋 

Turns out the comment menu was hidden on purpose ("it's not a bug, it's a feature" kind of thing): https://github.com/makaroni4/focused_youtube/commit/f4d1e803acad823a7359f028a54e295d4b932c68#diff-5a647dce088e657320242c053f646bfff8bf90d01f132f2ce25770640fe4a00eL289

Totally agree, let's bring it back 🙌 

I just published a new version (`1.20`), should be live in a couple of days 🤞
